server:
  port: 9001
spring:
  session:
    store-type: none
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/javastudy?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    redisson:
      config: classpath:redisson-${spring.profiles.active}.yml

mybatis:
  mapper-locations: classpath*:com/app/**/mapping/**/*.xml
  type-aliases-package: com.app.**.model
